### ISSUE TITLE
Additional card in main window showing the network hashrate

### ISSUE THREAD

**Issue by lemois-1337** [karlsen-network/karlsen-desktop#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It is very beneficial if miners will see the network hashrate in comparison to their device hashrate when running miner and node together on the same system. The hashrate has to be in human readable format, so automatic format for `KH/sec`,  `MH/sec`, `GH/sec`, `TH/sec` and `PH/sec` has to be calculated.

**Additional context**
See the screenshot below, where to add it:
![image](https://github.com/karlsen-network/karlsen-desktop/assets/151453086/04e94ca6-1678-4e9f-a97b-29cbaa8d123e)

**Comment by RoboticWF** [comment]
Any suggestions where to pull the miners hashrate from?

**Comment by lemois-1337** [comment]
The miner hashrate is already shown, when a miner is started. The node dashboard should also show the global network hashrate. It can be requested from `GetBlockDagInfo` gRPC call and some additional calculation, CLI example:

```
~# karlsenctl GetBlockDagInfo 
{
    "getBlockDagInfoResponse": {
        "networkName": "karlsen-mainnet",
        "blockCount": "190534",
        "headerCount": "7726849",
        "tipHashes": [
            "1e2ab01fc305cf3e782674f3bb2bf8c5f0fd2d6aeebe51933ce385292a7f91d2"
        ],
        "difficulty": 102993445633923.78,
        "pastMedianTime": "1706136665163",
        "virtualParentHashes": [
            "1e2ab01fc305cf3e782674f3bb2bf8c5f0fd2d6aeebe51933ce385292a7f91d2"
        ],
        "pruningPointHash": "af59a6315ffdbdbc6cf0f5bf343304e56def9c6005d4726b78e875872aa4a798",
        "virtualDaaScore": "6946012",
        "error": null
    }
}
```

Use `difficulty` multiply it with 2 and divide it by 1.000.000.000.000 to get the TH/sec. One-liner using `jq`:

```
~# echo "$(karlsenctl GetBlockDagInfo | jq '.getBlockDagInfoResponse.difficulty')*2/1000000000000" | bc -l
206.81829374176844000000
```
