### ISSUE TITLE
Window can't be moved on MacOS version

### ISSUE THREAD

**Issue by duderino999** [karlsen-network/karlsen-desktop#3]
**Describe the bug**
Window can't be moved. It can be minimized/maximized, but moving it is not possible. It is sticking to the top left corner.

**Desktop (please complete the following information):**
 - OS: MAC OS Ventura 13.6.3, MacBook Air M2
 - Wallet version: v1.0.0

**Comment by lemois-1337** [comment]
Could you try moving it by holding the Karlsen logo? Just tried on m1 machine and I can move it. I remember similar issue with different nwjs version but specifically manually tested it.

**Comment by duderino999** [comment]
confirming, its working by holding the Karlsen logo ... but only there.

**Comment by lemois-1337** [comment]
So you should also be able to move it when holding at the "Karlsen Desktop", "version" and the space between it and the tabs. You can't move it when you click and hold on the tabs. But that's expected and wanted.

**Comment by lemois-1337** [comment]
Thanks, closing then.
