### ISSUE TITLE
Will the new windows wallet for KARLSON be released before the fork? 

### ISSUE THREAD

**Issue by auroracoin** [karlsen-network/karlsen-desktop#8]
Will the new windows wallet for KARLSON algo v2 be released before the fork? thx

**Comment by lemois-1337** [comment]
Yes

**Comment by lemois-1337** [comment]
Available at: https://github.com/karlsen-network/karlsen-desktop/releases/tag/v2.0.0

**Comment by auroracoin** [comment]
Thx :)
